---
#Dock Items using dockutil

- name: Remove all items from the Dock
  command: dockutil --remove all
  tags: dock

- name: Set the default Dock items
  command: dockutil --add "{{ item }}"
  with_items:
    - /Applications/Safari.app
    - "/Applications/App Store.app"
    - "/Applications/System Preferences.app"
    - "/Applications/Google Chrome.app"
    - "/Applications/iTerm.app"
    - "/Applications/Visual Studio Code.app"
    - "/Applications/Messages.app"
  tags: dock
