---
# osx playbook

- name: "OS X Preferences"
  command: defaults write {{item.domain}} {{item.key}} {{item.value}}
  with_items: osx.prefs
  become: true
  become_user: "{{install_user}}"

- name: "Killing affected apps"
  command: killall {{item}}
  with_items:
    - "Dock"
    - "Finder"
    - "SystemUIServer"
