---
# install_homebrew

- name: "Check Homebrew path exists"
  stat: 
    path: /usr/local/Homebrew
  register: p
  
- name: "Create Homebrew Path"
  file: path=/usr/local/Homebrew state=directory owner="{{ install_user }}" group=staff
  when: p.stat.exists == False
  become: true

- name: "homebrew permissions"
  file: path=/usr/local state=directory owner="{{ install_user }}" group=staff
  when: p.stat.exists == False
  become: true

- name: "homebrew permissions"
  file: path=/usr/local/bin state=directory owner="{{ install_user }}" group=staff
  when: p.stat.exists == False
  become: true

- name: "Homebrew init"
  command: git init -q
  when: p.stat.exists == False
  args:
    chdir: /usr/local/Homebrew
    creates: /usr/local/Homebrew/.git

- name: "Homebrew origin"
  command: git config remote.origin.url https://github.com/Homebrew/brew.git
  when: p.stat.exists == False
  args:
    chdir: /usr/local/Homebrew

- name: "Homebrew fetch"
  command: git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  when: p.stat.exists == False
  args:
    chdir: /usr/local/Homebrew

- name: "Homebrew fetch master"
  command: "git fetch origin master:refs/remotes/origin/master -n --depth=1"
  when: p.stat.exists == False
  args:
    chdir: /usr/local/Homebrew

- name: "Homebrew reset"
  command: "git reset --hard origin/master"
  when: p.stat.exists == False
  args:
    chdir: /usr/local/Homebrew

- name: "Link Brew"
  file: src=/usr/local/Homebrew/bin/brew dest=/usr/local/bin/brew state=link owner="{{ install_user }}" group=staff
  when: p.stat.exists == False
  become: true
