---
# brew playbook

- include: install_homebrew.yml

- name: "update Homebrew"
  homebrew: state=latest
  tags: update

- name: "Install Homebrew packages"
<<<<<<< HEAD
  homebrew: name={{item.package}} install_options={{item.options | default("") }} state=latest
  with_items: "{{ brew.packages }}"
=======
  homebrew: name="{{item.package}}" install_options="{{item.options | default("") }}" state=latest
  with_items: brew.packages
>>>>>>> fixed syntax for variables in ansible2
  tags: update
