---
# brew playbook

- include: install_homebrew.yml
  tags: bootstrap

- name: "update Homebrew"
  homebrew: state=latest
  tags: bootstrap

- name: "Install the minimum Homebrew packages"
  homebrew: name="{{item.package}}" install_options="{{item.options | default("") }}" state=latest
  with_items: "{{brew.packages_min}}"
  tags: bootstrap

- name: "Install all the Homebrew packages"
  homebrew: name="{{item.package}}" install_options="{{item.options | default("") }}" state=latest
  with_items: "{{brew.packages}}"
