---
# brew playbook

- name: "Check Homebrew path exists"
  stat: 
    path: /usr/local/Homebrew
  register: p
  
- name: "Create Homebrew Path"
  file: path=/usr/local/Homebrew state=directory owner="{{ install_user }}" group=staff
  when: p.stat.exists == False
  become: true

- name: "homebrew bin permissions"
  file: path=/usr/local/bin state=directory owner="{{ install_user }}" group=staff
  when: p.stat.exists == False
  become: true

- name: "homebrew var permissions"
  file: path=/usr/local/var state=directory owner="{{ install_user }}" group=staff
  when: p.stat.exists == False
  become: true

- name: "homebrew Cellar permissions"
  file: path=/usr/local/Cellar state=directory owner="{{ install_user }}" group=staff
  when: p.stat.exists == False
  become: true

- name: "homebrew Frameworks permissions"
  file: path=/usr/local/Frameworks state=directory owner="{{ install_user }}" group=staff
  when: p.stat.exists == False
  become: true

- name: "homebrew include permissions"
  file: path=/usr/local/include state=directory owner="{{ install_user }}" group=staff
  when: p.stat.exists == False
  become: true

- name: "homebrew lib permissions"
  file: path=/usr/local/lib state=directory owner="{{ install_user }}" group=staff
  when: p.stat.exists == False
  become: true

- name: "homebrew share permissions"
  file: path=/usr/local/share state=directory owner="{{ install_user }}" group=staff
  when: p.stat.exists == False
  become: true

- name: "homebrew Caskroom permissions"
  file: path=/usr/local/Caskroom state=directory owner="{{ install_user }}" group=staff
  when: p.stat.exists == False
  become: true

- name: "homebrew etc permissions"
  file: path=/usr/local/etc state=directory owner="{{ install_user }}" group=staff
  when: p.stat.exists == False
  become: true

- name: "homebrew opt permissions"
  file: path=/usr/local/opt state=directory owner="{{ install_user }}" group=staff
  when: p.stat.exists == False
  become: true

- name: "Homebrew init"
  command: git init -q
  when: p.stat.exists == False
  args:
    chdir: /usr/local/Homebrew
    creates: /usr/local/Homebrew/.git

- name: "Homebrew origin"
  command: git config remote.origin.url https://github.com/Homebrew/brew.git
  when: p.stat.exists == False
  args:
    chdir: /usr/local/Homebrew

- name: "Homebrew fetch"
  command: git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  when: p.stat.exists == False
  args:
    chdir: /usr/local/Homebrew

- name: "Homebrew fetch master"
  command: "git fetch origin master:refs/remotes/origin/master -n --depth=1"
  when: p.stat.exists == False
  args:
    chdir: /usr/local/Homebrew

- name: "Homebrew reset"
  command: "git reset --hard origin/master"
  when: p.stat.exists == False
  args:
    chdir: /usr/local/Homebrew

- name: "Link Brew"
  file: src=/usr/local/Homebrew/bin/brew dest=/usr/local/bin/brew state=link owner="{{ install_user }}" group=staff
  when: p.stat.exists == False
  become: true

- name: "update Homebrew"
  community.general.homebrew: state=latest

- name: "Tap Homebrew repos"
  homebrew_tap: name="{{item}}" state=present
  with_items: "{{brew.taps}}"
  ignore_errors: yes

- name: "Install all the Homebrew packages"
  community.general.homebrew: name="{{item.package}}" install_options="{{item.options | default("") }}" state=latest
  with_items: "{{brew.packages}}"
  ignore_errors: yes
