---
- name: restart AppStore
  command: killall "App Store"
  ignore_errors: yes

- name: restart MenuBar
  command: killall SystemUIServer
  ignore_errors: yes

- name: restart Dock
  command: killall Dock
  ignore_errors: yes

- name: restart Finder
  command: killall Finder
  ignore_errors: yes

- name: restart Safari
  command: killall Safari
  ignore_errors: yes
