---
# dotfiles playbook

- name: "Check if dotfiles exists"
  stat:
    path: /Users/{{install_user}}/.dotfiles
  register: j

- name: "Check if vimfiles path exists"
  stat:
    path: /Users/{{install_user}}/.vimfiles
  register: v

- name: "Check if vscode path exists"
  stat:
    path: /Users/{{install_user}}/.vscode
  register: vs

- name: "Clone dotfiles repo"
  git: repo=https://github.com/mjwalf/dotfiles.git dest=/Users/{{install_user}}/.dotfiles recursive=yes
  when: j.stat.exists == False

- name: "Clone oh-my-zsh from robbyrussell repo"
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/Users/{{install_user}}/.oh-my-zsh recursive=yes
  when: j.stat.exists == False

- name: "Check zsh is cloned"
  stat:
    path: /Users/{{install_user}}/.oh-my-zsh
  register: z

- name: "clone zsh autosuggestions"
  git: repo=https://github.com/zsh-users/zsh-completions.git dest=/Users/{{install_user}}/.oh-my-zsh/custom/plugins/zsh-completions recursive=yes
  when: z.stat.exists == True

- name: "Link Dot files"
  file: src=/Users/{{install_user}}/.dotfiles/{{ item.path }} dest=/Users/{{install_user}}/{{ item.dest }} state=link force=yes
  with_items:
    - { path: "tmux.conf", dest: ".tmux.conf" }
    - { path: "gitconfig", dest: ".gitconfig" }
    - { path: "zsh/zshrc", dest: ".zshrc" }

- name: "Link vscode files"
  when: vs.stat.exists == False
  file: src=/Users/{{install_user}}/.dotfiles/{{item.path}} dest=/Users/{{install_user}}/{{ item.dest }} state=link force=yes
  with_items:
    - { path: "vscode", dest: ".vscode" }

- name: "Install font"
  file: src="/Users/{{install_user}}/.dotfiles/fonts/Droid Sans Mono for Powerline.otf" dest="/Users/{{install_user}}/Library/Fonts/Droid Sans Mono for Powerline.otf" state=link
  when: j.stat.exists == False

- name: "Add Zshell"
  lineinfile: dest=/etc/shells line='/usr/local/bin/zsh'
  become: true

- name: "Change default shell to zsh"
  command: chsh -s /usr/local/bin/zsh "{{install_user}}"
  become: true
