---
# dotfiles playbook

- name: "Clone dotfiles"
  git: repo=git@bitbucket.org:mjwalf/dotfiles.git dest=/Users/{{install_user}}/.dotfiles recursive=yes

- name: "Link files"
  file: src=/Users/{{install_user}}/.dotfiles/{{ item.path }} dest=/Users/{{install_user}}/{{ item.dest }} state=link
  with_items:
    - { path: "tmux.conf", dest: ".tmux.conf" }
    - { path: "gitconfig", dest: ".gitconfig" }
    - { path: "zsh/zshrc", dest: ".zshrc" }
    - { path: "oh-my-zsh/zshrc", dest: ".oh-my-zsh" }

- name: "Install font"
  file: src="/Users/{{install_user}}/.dotfiles/fonts/Droid Sans Mono for Powerline.otf" dest="/Users/{{install_user}}/Library/Fonts/Droid Sans Mono for Powerline.otf" state=link

- name: "add shell"
  lineinfile: dest=/etc/shells line='/usr/local/bin/zsh'
  become: true

- name: "change shell"
  command: chsh -s /usr/local/bin/zsh {{install_user}}
  become: true
