---
- name: "Bluetooth - Check if Bluetooth is already in menu bar"
  command: "defaults read com.apple.systemuiserver menuExtras"
  register: result
  changed_when: False

- name: "Bluetooth - Show Bluetooth in menu bar"
  command: defaults write com.apple.systemuiserver menuExtras -array-add "/System/Library/CoreServices/Menu Extras/Bluetooth.menu"
  when: Bluetooth_ShowInMenuBar is defined and Bluetooth_ShowInMenuBar == "true" and 'Bluetooth.menu' not in result.stdout
  notify: restart MenuBar

# TODO: support remove from menubar
