---
- name: "Date Time - Get the current timezone"
  command: "systemsetup -gettimezone"
  become: true
  register: result
  changed_when: False
  when: DateTime_TimeZone is defined

- name: "Date Time - Set the timezone"
  command: "systemsetup -settimezone '{{DateTime_TimeZone}}'"
  become: true
  when: DateTime_TimeZone is defined and DateTime_TimeZone not in result.stdout
  notify: restart MenuBar

- name: "Date Time - Set date and time automatically"
  command: "systemsetup -setusingnetworktime {{DateTime_AutomaticDateTime}}"
  become: true
  when: DateTime_AutomaticDateTime is defined
  register: result
  changed_when: "'already' not in result.stdout"
  notify: restart MenuBar

- name: "Date Time - Get the current time server"
  command: "systemsetup -getnetworktimeserver"
  become: true
  register: result
  changed_when: False
  when: DateTime_TimeServer is defined
- name: "Date Time - Set time server"
  command: "systemsetup -setnetworktimeserver '{{DateTime_TimeServer}}'"
  become: true
  when: DateTime_TimeServer is defined and DateTime_TimeServer not in result.stdout
  notify: restart MenuBar

- name: "Date Time - Set time zome automatically using current location"
  osx_defaults: { domain: '/Library/Preferences/com.apple.timezone.auto.plist', key: 'Active', type: bool, value: "{{DateTime_AutomaticTimeZone}}" }
  become: true
  when: DateTime_AutomaticTimeZone is defined
  notify: restart MenuBar

- name: "Date Time - Menu bar clock format"
  osx_defaults: { domain: 'com.apple.menuextra.clock', key: 'DateFormat', type: string, value: "{{DateTime_DateFormat}}" }
  when: DateTime_DateFormat is defined
  notify: restart MenuBar

- name: "Date Time - Flash the time separators"
  osx_defaults: { domain: 'com.apple.menuextra.clock', key: 'FlashDateSeparators', type: bool, value: "{{DateTime_FlashDateSeparators}}" }
  when: DateTime_FlashDateSeparators is defined
  notify: restart MenuBar

- name: "Date Time - Analog menu bar clock"
  osx_defaults: { domain: 'com.apple.menuextra.clock', key: 'IsAnalog', type: bool, value: "{{DateTime_IsAnalog}}" }
  when: DateTime_IsAnalog is defined
  notify: restart MenuBar
