---
- name: "Finder - General - Show hard disks on the desktop"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowHardDrivesOnDesktop
    type: bool
    value: "{{ Finder_ShowHardDrivesOnDesktop }}"
  when: Finder_ShowHardDrivesOnDesktop is defined
  notify: restart Finder

- name: "Finder - General - Show external disks on the desktop"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowExternalHardDrivesOnDesktop
    type: bool
    value: "{{ Finder_ShowExternalHardDrivesOnDesktop }}"
  when: Finder_ShowExternalHardDrivesOnDesktop is defined
  notify: restart Finder

- name: "Finder - General - Show CDs, DVDs and iPods on the desktop"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowRemovableMediaOnDesktop
    type: bool
    value: "{{ Finder_ShowRemovableMediaOnDesktop }}"
  when: Finder_ShowRemovableMediaOnDesktop is defined
  notify: restart Finder

- name: "Finder - General - Show connected servers on the desktop"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowMountedServersOnDesktop
    type: bool
    value: "{{ Finder_ShowMountedServersOnDesktop }}"
  when: Finder_ShowMountedServersOnDesktop is defined
  notify: restart Finder

- name: "Finder - General - New Finder windows show (target)"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: NewWindowTarget
    type: string
    value: "{{ Finder_NewWindowTarget }}"
  when: Finder_NewWindowTarget is defined
  register: nw_target
  notify: restart Finder

- name: "Finder - General - New Finder windows show (path)"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: NewWindowTargetPath
    type: string
    value: "{{ item.value }}"
  loop:
    - { name: "PfCm", value: "" }
    - { name: "PfVo", value: "file:///" }
    - { name: "PfHm", value: "file://{{ ansible_env.HOME }}/" }
    - { name: "PfDe", value: "file://{{ ansible_env.HOME }}/Desktop/" }
    - { name: "PfDo", value: "file://{{ ansible_env.HOME }}/Documents/" }
    - { name: "PfAF", value: "file:///System/Library/CoreServices/Finder.app/Contents/Resources/MyLibraries/myDocuments.cannedSearch" }
  when:
    - Finder_NewWindowTarget is defined
    - item.name == Finder_NewWindowTarget
  notify: restart Finder

- name: "Finder - General - Open folders in tabs instead of new windows"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FinderSpawnTab
    type: bool
    value: "{{ Finder_FinderSpawnTab }}"
  when: Finder_FinderSpawnTab is defined
  notify: restart Finder

- name: "Finder - Advanced - Show all filename extensions"
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: "{{ Finder_AppleShowAllExtensions }}"
  when: Finder_AppleShowAllExtensions is defined
  notify: restart Finder

- name: "Finder - Advanced - Show warning before changing an extension"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: "{{ Finder_FXEnableExtensionChangeWarning }}"
  when: Finder_FXEnableExtensionChangeWarning is defined
  notify: restart Finder

- name: "Finder - Advanced - Show warning before emptying the trash"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: WarnOnEmptyTrash
    type: bool
    value: "{{ Finder_WarnOnEmptyTrash }}"
  when: Finder_WarnOnEmptyTrash is defined
  notify: restart Finder

- name: "Finder - Advanced - Default search scope"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: "{{ Finder_FXDefaultSearchScope }}"
  when: Finder_FXDefaultSearchScope is defined
  notify: restart Finder

- name: "Finder - View - View as"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: "{{ Finder_FXPreferredViewStyle }}"
  when: Finder_FXPreferredViewStyle is defined
  notify: restart Finder

- name: "Finder - View - Arrange By"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXPreferredGroupBy
    type: string
    value: "{{ Finder_FXPreferredGroupBy }}"
  when: Finder_FXPreferredGroupBy is defined
  notify: restart Finder

- name: "Finder - View - Show Tab Bar"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowTabView
    type: bool
    value: "{{ Finder_ShowTabView }}"
  when: Finder_ShowTabView is defined
  notify: restart Finder

- name: "Finder - View - Show Path Bar"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: "{{ Finder_ShowPathbar }}"
  when: Finder_ShowPathbar is defined
  notify: restart Finder

- name: "Finder - View - Show Status Bar"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: "{{ Finder_ShowStatusBar }}"
  when: Finder_ShowStatusBar is defined
  notify: restart Finder

- name: "Finder - View - Show Side Bar"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowSidebar
    type: bool
    value: "{{ Finder_ShowSidebar }}"
  when: Finder_ShowSidebar is defined
  notify: restart Finder

- name: "Finder - View - Show Preview"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ColumnShowIcons
    type: bool
    value: "{{ Finder_ColumnShowIcons }}"
  when: Finder_ColumnShowIcons is defined
  notify: restart Finder

- name: "Finder - Extra - Show full POSIX path as Finder window title"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: _FXShowPosixPathInTitle
    type: bool
    value: "{{ Finder_FXShowPosixPathInTitle }}"
  when: Finder_FXShowPosixPathInTitle is defined
  notify: restart Finder

- name: "Finder - Extra - Show Hidden Files"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: "{{ Finder_AppleShowAllFiles }}"
  when: Finder_AppleShowAllFiles is defined
  notify: restart Finder
