---
- name: "General - Set appearance"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'AppleAquaColorVariant', type: int, value: "{{ General_AppleAquaColorVariant }}" }
  when: General_AppleAquaColorVariant is defined

- name: "General - Use Dark menu bar and Dock"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'AppleInterfaceStyle', type: string, value: "{{ General_AppleInterfaceStyle }}" }
  when: General_AppleInterfaceStyle is defined
  notify:
    - restart MenuBar
    - restart Dock

- name: "General - Automatically hide and show the menu bar"
  osx_defaults: { domain: 'NSGlobalDomain', key: '_HIHideMenuBar', type: bool, value: "{{ General_AutoHideMenuBar }}" }
  when: General_AutoHideMenuBar is defined
  notify: restart MenuBar

- name: "General - Highlight color"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'AppleHighlightColor', type: string, value: "{{ item.value }}" }
  with_items:
    - { name: Red, value: "1.000000 0.733333 0.721569" }
    - { name: Orange, value: "1.000000 0.874510 0.701961" }
    - { name: Yellow, value: "1.000000 0.937255 0.690196" }
    - { name: Green, value: "0.752941 0.964706 0.678431" }
    - { name: Blue, value: "0.695422 0.843986 0.997528" }
    - { name: Purple, value: "0.968627 0.831373 1.000000" }
    - { name: Pink, value: "1.000000 0.749020 0.823529" }
    - { name: Brown, value: "0.929412 0.870588 0.792157" }
    - { name: Graphite, value: "0.847059 0.847059 0.862745" }
  when: General_AppleHighlightColor is defined and item.name == General_AppleHighlightColor

- name: "General - Sidebar icon size"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'NSTableViewDefaultSizeMode', type: int, value: "{{ General_SidebarIconSize }}" }
  when: General_SidebarIconSize is defined

- name: "General - Scroll bar visibility"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'AppleShowScrollBars', type: string, value: "{{ General_AppleShowScrollBars }}" }
  when: General_AppleShowScrollBars is defined

- name: "General - Scroll bar click behavior"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'AppleScrollerPagingBehavior', type: bool, value: "{{ General_AppleScrollerPagingBehavior }}" }
  when: General_AppleScrollerPagingBehavior is defined

- name: "General - Ask to keep changes when closing documents"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'NSCloseAlwaysConfirmsChanges', type: bool, value: "{{ General_NSCloseAlwaysConfirmsChanges }}" }
  when: General_NSCloseAlwaysConfirmsChanges is defined

- name: "General - Close windows when quitting an application"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'NSQuitAlwaysKeepsWindows', type: bool, value: "{{ not General_CloseWindowsWhenQuittingApp }}" }
  when: General_CloseWindowsWhenQuittingApp is defined
  
- name: "General - Extra - Smooth scrolling"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'NSScrollAnimationEnabled', type: bool, value: "{{ General_NSScrollAnimationEnabled }}" }
  when: General_NSScrollAnimationEnabled is defined
