---
- name: "iCloud - Save to iCloud by default"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'NSDocumentSaveNewDocumentsToCloud', type: bool, value: "{{ ICloud_NSDocumentSaveNewDocumentsToCloud }}" }
  when: ICloud_NSDocumentSaveNewDocumentsToCloud is defined
