---
- name: "Language & Region - Prefered languages (in order of preference {{ LanguageRegion_Languages }}"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'AppleLocale', type: array, value: "{{ LanguageRegion_Languages }}" }
  when: LanguageRegion_Languages is defined

- name: "Language & Region - Locale and Currency"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'AppleLocale', type: string, value: "{{ LanguageRegion_Locale }}" }
  when: LanguageRegion_Locale is defined

- name: "Language & Region - Measure Units"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'AppleMeasurementUnits', type: string, value: "{{ LanguageRegion_MeasurementUnits }}" }
  when: LanguageRegion_MeasurementUnits is defined

- name: "Language & Region - Force 12/24 hour time"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'AppleICUForce24HourTime', type: bool, value: "{{ LanguageRegion_Force24HourTime }}" }
  when: LanguageRegion_Force24HourTime is defined

- name: "Language & Region - Set Metric Units"
  osx_defaults: { domain: 'NSGlobalDomain', key: 'AppleMetricUnits', type: bool, value: "{{ LanguageRegion_MetricUnits }}" }
  when: LanguageRegion_MetricUnits is defined
