---
# Taps and Casks

- name: "Check Homebrew path exists"
  stat: 
    path: /usr/local/Homebrew
  register: p

- name: "Update Homebrew"
  when: p.stat.exists == False
  homebrew: update_homebrew=yes

- name: "Upgrade Homebrew"
  when: p.stat.exists == False
  homebrew: state=latest

- name: "Tap Homebrew repos"
  homebrew_tap: name="{{item}}" state=present
  with_items: "{{ casks.taps }}"

- name: "Install Casks (bootstrap)"
  homebrew_cask: name="{{item}}" install_options="force" state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir=/Applications"
  with_items: "{{ casks.packages_min }}"
  tags: bootstrap

- name: "Install Casks"
  homebrew_cask: name="{{item}}" install_options="force" state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir=/Applications"
  with_items: "{{ casks.packages }}"
