---
# Taps and Casks

- name: "Check Homebrew path exists"
  stat: 
    path: /usr/local/Homebrew
  register: p

- name: "Update Homebrew"
  homebrew: update_homebrew=yes
  when: p.stat.exists == False

- name: "Upgrade Homebrew"
  homebrew: state=latest
  when: p.stat.exists == False

- name: "Tap Homebrew repos"
  homebrew_tap: name="{{item}}" state=present
  with_items: "{{ casks.taps }}"

- name: "Install Casks"
  homebrew_cask: name="{{item}}" install_options="force" state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir=/Applications"
  with_items: "{{ casks.packages }}"
  ignore_errors: yes
