---
# cask playbook

- name: "Tap Homebrew repos"
  homebrew_tap: name="{{item}}" state=present
  with_items: "{{ casks.taps }}"

- name: "update Homebrew"
  homebrew: update_homebrew=yes

- name: "update Homebrew"
  homebrew: state=latest

- name: "Install Base Casks"
  homebrew_cask: name="{{item}}" install_options="force" state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir=/Applications"
  with_items: "{{ casks.packages_min }}"
  tags: bootstrap

- name: "Install Casks"
  homebrew_cask: name="{{item}}" install_options="force" state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir=/Applications"
  with_items: "{{ casks.packages }}"
  tags: allcasks
