---
# Playbook file

- name: brew
  hosts: laptop
  roles:
    - brew
  tags:
    - brew

- name: casks
  hosts: laptop
  roles:
    - casks
  tags:
    - casks

- name: dotfiles
  hosts: laptop
  roles:
    - dotfiles
  tags:
    - dotfiles

- name: macos
  hosts: laptop
  vars_files:
    - vars/macos.yml
  roles: 
    - macos
  tags:
    - macos

- name: dock
  hosts: laptop
  roles:
    - dock
  tags:
    - dock
