---
# Playbook file

- name: osx
  hosts: laptop
  roles:
    - osx

- name: brew
  hosts: laptop
  roles:
    - brew

- name: casks
  hosts: laptop
  roles:
    - casks
  tags:
    - update

- name: dotfiles
  hosts: laptop
  roles:
    - dotfiles
  tags:
    - update

- name: vimfiles
  hosts: laptop
  roles:
    - vimfiles
  tags:
    - update