---
# vimfiles playbook

- name: "Check vimfiles path exists"
  stat: 
    path: /Users/{{install_user}}/.vimfiles
  register: v

- name: "Clone vimfiles"
  git: repo=https://github.com/sthulb-attic/vimfiles.git dest=/Users/{{install_user}}/.vimfiles recursive=yes
  when: v.stat.exists == False

- name: "Link files"
  when: v.stat.exists == False
  file: src=/Users/{{install_user}}/.vimfiles/{{item.path}} dest=/Users/{{install_user}}/{{ item.dest }} state=link force=yes
  with_items:
    - { path: "vimrc.vim", dest: ".vimrc" }
    - { path: "plugins", dest: ".vim" }

- name: "Install vundle"
  when: v.stat.exists == False
  git: repo=https://github.com/VundleVim/Vundle.vim.git dest=/Users/{{install_user}}/.vimfiles/plugins/bundle/Vundle.vim recursive=yes

